/**
 * Offline cache.
 *
 * GENERATED by tools/build-sw.mjs — do not edit by hand, re-run it.
 *
 * Precaches every file the two pages need, so the app works with the network
 * switched off. It answers only with same-origin bytes it already holds: no
 * request is added, and "no network after load" (§7) is strengthened, not
 * weakened.
 *
 * Cache-first, because none of these files change without the version below
 * changing with them — the version is a hash of their contents.
 */

const VERSION = '257c24cc4c08';
const CACHE = `meishiki-${VERSION}`;

const FILES = [
  "./",
  "index.html",
  "voice.html",
  "manifest.webmanifest",
  "app/style.css",
  "vendor/swisseph-wasm/src/swisseph.js",
  "vendor/swisseph-wasm/wasm/swisseph.js",
  "vendor/swisseph-wasm/wasm/swisseph.wasm",
  "vendor/swisseph-wasm/wasm/swisseph.data",
  "app/engine/agreement.js",
  "app/engine/agreementRates.js",
  "app/engine/chart.js",
  "app/engine/compass.js",
  "app/engine/domains.js",
  "app/engine/gauges.js",
  "app/engine/glance.js",
  "app/engine/hidden.js",
  "app/engine/kyusei.js",
  "app/engine/luck.js",
  "app/engine/lunar.js",
  "app/engine/name.js",
  "app/engine/numerology.js",
  "app/engine/oracle.js",
  "app/engine/pillars.js",
  "app/engine/places.js",
  "app/engine/plainwords.js",
  "app/engine/rarity.js",
  "app/engine/reading.js",
  "app/engine/shukuyo.js",
  "app/engine/strength.js",
  "app/engine/strokes.js",
  "app/engine/swe.js",
  "app/engine/systems.js",
  "app/engine/tenGods.js",
  "app/engine/terms.js",
  "app/engine/time.js",
  "app/engine/timeline.js",
  "app/engine/uncertainty.js",
  "app/engine/voice.js",
  "app/engine/western.js",
  "app/icons/apple-touch-icon.png",
  "app/icons/icon-192.png",
  "app/icons/icon-512.png",
  "app/icons/icon-maskable-512.png",
  "app/icons/icon.svg",
  "app/layers-main.js",
  "app/main.js",
  "app/oracle-main.js",
  "app/ui/board.js",
  "app/ui/dial.js",
  "app/ui/glance.js",
  "app/ui/luckband.js",
  "app/ui/placefield.js",
  "app/ui/render.js",
  "app/ui/sky.js",
  "app/ui/wuxing.js",
  "app/voice-main.js"
];

self.addEventListener('install', (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    // addAll is atomic: one 404 and the whole install fails, which is what we
    // want. A half-populated cache is the blank-screen failure.
    await cache.addAll(FILES);
    await self.skipWaiting();
  })());
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    for (const key of await caches.keys()) {
      if (key.startsWith('meishiki-') && key !== CACHE) await caches.delete(key);
    }
    await self.clients.claim();
  })());
});

self.addEventListener('fetch', (event) => {
  const { request } = event;
  if (request.method !== 'GET') return;

  const url = new URL(request.url);
  // Same-origin only. The app makes no cross-origin requests, and a worker that
  // would proxy one is a worker that could hide one.
  if (url.origin !== self.location.origin) return;

  event.respondWith((async () => {
    const cached = await caches.match(request, { ignoreSearch: true });
    if (cached) return cached;
    try {
      return await fetch(request);
    } catch {
      // Offline and not in the cache: a navigation still gets the board page
      // rather than the browser's error screen.
      if (request.mode === 'navigate') {
        const shell = await caches.match('index.html');
        if (shell) return shell;
      }
      throw new Error('offline and not cached');
    }
  })());
});
