/**
 * How often two systems point the same way, measured over 20,000 random births.
 *
 * GENERATED by tools/build-agreement.mjs — do not edit by hand, re-run it.
 *
 * Each value is the share of the births **where both systems answered** that
 * they answered the same. The denominator matters: a projection declines on a
 * record it cannot support (no ascendant without a birth time), and counting
 * those as disagreements would understate every rate involving them.
 *
 * Read these as the null hypothesis. An agreement occurring at the rate below
 * is what agreement looks like when it means nothing.
 */

export const AGREEMENT_SAMPLES = 20000;

/** JST date these rates were counted on. */
export const AGREEMENT_COUNTED_ON = '2026-07-31';

export const AGREEMENT_RATES = {
  "meishiki:needed|kyusei:year": {
    "observed": 0.2071,
    "independent": 0.20772,
    "checked": 20000
  },
  "meishiki:needed|kyusei:month": {
    "observed": 0.2302,
    "independent": 0.21035,
    "checked": 20000
  },
  "meishiki:dominant|kyusei:year": {
    "observed": 0.18653,
    "independent": 0.22702,
    "checked": 13912
  },
  "meishiki:dominant|kyusei:month": {
    "observed": 0.17431,
    "independent": 0.22917,
    "checked": 13912
  },
  "meishiki:polarity|western:sun": {
    "observed": 0.51787,
    "independent": 0.49979,
    "checked": 13289
  },
  "meishiki:polarity|western:moon": {
    "observed": 0.49199,
    "independent": 0.5,
    "checked": 13289
  },
  "meishiki:polarity|numerology:polarity": {
    "observed": 0.49959,
    "independent": 0.50317,
    "checked": 13289
  },
  "western:sun|numerology:polarity": {
    "observed": 0.497,
    "independent": 0.49623,
    "checked": 20000
  },
  "western:moon|numerology:polarity": {
    "observed": 0.50195,
    "independent": 0.50169,
    "checked": 20000
  }
};

/**
 * Measured rates for a pair, or null when it was never measured.
 *
 * `observed` is how often the two agreed. `independent` is how often they would
 * have agreed if unrelated, from their own answer distributions. When the two
 * are close, the agreement carries no information, and the reading says so.
 */
export function agreementRate(key) {
  return Object.prototype.hasOwnProperty.call(AGREEMENT_RATES, key) ? AGREEMENT_RATES[key] : null;
}

/**
 * How much an agreement beats chance, as a ratio. 1.0 is exactly chance.
 *
 * Deliberately not dressed up as a p-value: with 20,000 samples almost any
 * difference is "significant", and significance is not the question. The
 * question is whether the lift is large enough for a person to care, and a
 * ratio lets them decide that themselves.
 */
export function lift(key) {
  const r = agreementRate(key);
  return r && r.independent > 0 ? r.observed / r.independent : null;
}
