/**
 * Measure how often each reading statement occurs, and write the table the
 * reading layer cites.
 *
 * Telling a reader that a configuration appears in about one chart in four is
 * the honest version of "this is significant". It is computed, not asserted,
 * and it works against the Barnum effect rather than for it: a statement that
 * turns out to be near-universal is labelled as such instead of being dressed
 * up as personal insight.
 *
 * Run:  node tools/build-rarity.mjs [samples]
 * Writes app/engine/rarity.js. Re-run it whenever a rule changes.
 */

import { writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

import { initEphemeris } from '../app/engine/swe.js';
import { buildChart, DEFAULT_AXES } from '../app/engine/chart.js';
import { rawStatements } from '../app/engine/reading.js';
import { voiceStatements } from '../app/engine/voice.js';
import { julianDay } from '../app/engine/swe.js';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SAMPLES = Number(process.argv[2]) || 20000;

await initEphemeris();

// The 年運 passage compares the chart against the solar year in progress, so
// its frequency is necessarily "as of now" — it answers "this year, how many
// people are in a pressure year", which is exactly what it should mean.
const now = new Date();
const nowJdUt = julianDay(
  now.getUTCFullYear(), now.getUTCMonth() + 1, now.getUTCDate(),
  now.getUTCHours() + now.getUTCMinutes() / 60,
);

let seed = 20260729;
const rnd = (a, b) => {
  seed = (seed * 1103515245 + 12345) & 0x7fffffff;
  return a + (seed % (b - a + 1));
};

const counts = new Map();

for (let i = 0; i < SAMPLES; i += 1) {
  const chart = buildChart({
    year: rnd(1930, 2030), month: rnd(1, 12), day: rnd(1, 28),
    hour: rnd(0, 23), minute: rnd(0, 59), precision: 'pm5',
    longitude: 122 + rnd(0, 3200) / 100,
  }, DEFAULT_AXES);

  // A chart counts once per distinct key, not once per statement, so a rule
  // that fires twice on one chart does not inflate its own frequency.
  // Both layers are measured into one table: the 語り page cites the same
  // frequencies, and it needs them most.
  const seen = new Set([
    ...rawStatements(chart).map((s) => s.key),
    ...voiceStatements(chart, nowJdUt).map((s) => s.key),
  ]);
  for (const key of seen) counts.set(key, (counts.get(key) || 0) + 1);
}

const table = Object.fromEntries(
  [...counts.entries()]
    .sort((a, b) => a[1] - b[1])
    .map(([key, n]) => [key, Number((n / SAMPLES).toFixed(5))]),
);

const body = `/**
 * How often each reading statement occurs, measured over ${SAMPLES.toLocaleString('en-US')} random charts.
 *
 * GENERATED by tools/build-rarity.mjs — do not edit by hand, re-run it.
 *
 * Both the board reading and the 語り page cite these, so a reader can tell an
 * unusual configuration from a near-universal one. Without them, "月支が午で火"
 * reads as a personal revelation when it is true of a twelfth of everybody.
 *
 * Keys beginning voiceYear: are relative to the solar year this table was
 * built in, because that is what a year reading is about.
 */

export const RARITY_SAMPLES = ${SAMPLES};

export const RARITY = ${JSON.stringify(table, null, 2)};

/** Frequency of a statement key, or null when it was never measured. */
export function frequencyOf(key) {
  return Object.prototype.hasOwnProperty.call(RARITY, key) ? RARITY[key] : null;
}
`;

writeFileSync(join(ROOT, 'app/engine/rarity.js'), body);

console.log(`measured ${counts.size} distinct statement keys over ${SAMPLES} charts`);
console.log('\nrarest 10:');
for (const [key, freq] of Object.entries(table).slice(0, 10)) {
  console.log(`  ${(freq * 100).toFixed(2).padStart(6)}%  ${key}`);
}
console.log('\nmost common 10:');
for (const [key, freq] of Object.entries(table).slice(-10)) {
  console.log(`  ${(freq * 100).toFixed(2).padStart(6)}%  ${key}`);
}
console.log('\nwrote app/engine/rarity.js');
