/**
 * Build the stroke-count table the name reading uses.
 *
 * Source: KANJIDIC2 (Electronic Dictionary Research and Development Group,
 * CC BY-SA 4.0) — <stroke_count>, the count Japanese dictionaries give.
 *
 * Why not Unihan: its kTotalStrokes follows the Chinese form, and for the
 * radicals 辶 and 阝 it disagrees with Japanese practice on exactly the
 * characters that matter here. It gives 郎 as 8 where a Japanese dictionary
 * gives 9, and 郎 is about as common in Japanese given names as a character
 * gets. Checked against 21 known characters: Unihan 19/21, KANJIDIC2 21/21.
 *
 *   node tools/build-strokes.mjs path/to/kanjidic2.xml
 *
 * Writes app/engine/strokes.js. The table is grouped by stroke count, so the
 * characters themselves are the only payload.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const source = process.argv[2];
if (!source) {
  console.error('usage: node tools/build-strokes.mjs <kanjidic2.xml>');
  process.exit(1);
}

const xml = readFileSync(source, 'utf8');
const byCount = new Map();
let total = 0;

for (const entry of xml.match(/<character>[\s\S]*?<\/character>/g) || []) {
  const literal = entry.match(/<literal>(.)<\/literal>/);
  // The first stroke_count is the accepted count; later ones are common
  // miscounts that KANJIDIC records for lookup tolerance.
  const count = entry.match(/<stroke_count>(\d+)<\/stroke_count>/);
  if (!literal || !count) continue;
  const n = Number(count[1]);
  if (!byCount.has(n)) byCount.set(n, []);
  byCount.get(n).push(literal[1]);
  total += 1;
}

const table = {};
for (const n of [...byCount.keys()].sort((a, b) => a - b)) {
  table[n] = byCount.get(n).join('');
}

const body = `/**
 * Kanji stroke counts, grouped by count.
 *
 * GENERATED by tools/build-strokes.mjs — do not edit by hand.
 *
 * Source: KANJIDIC2, Electronic Dictionary Research and Development Group,
 * used under CC BY-SA 4.0. <https://www.edrdg.org/wiki/index.php/KANJIDIC_Project>
 * ${total} characters.
 *
 * These are the counts a Japanese dictionary gives (新字体). 姓名判断 schools
 * that count 旧字体 will differ on characters like 邊 and 齋, and the reading
 * says so rather than pretending there is one answer.
 */

export const STROKES_BY_COUNT = ${JSON.stringify(table, null, 0)};

const LOOKUP = new Map();
for (const [count, chars] of Object.entries(STROKES_BY_COUNT)) {
  for (const ch of chars) LOOKUP.set(ch, Number(count));
}

/**
 * Kana, by the count of strokes it takes to write them.
 *
 * This is the convention most 姓名判断 schools use, but agreement is weaker
 * here than for kanji — some schools count は as 3 rather than 6. Stated as a
 * choice rather than presented as fact.
 */
const KANA = {
  あ: 3, い: 2, う: 2, え: 3, お: 4, か: 3, き: 4, く: 2, け: 3, こ: 2,
  さ: 3, し: 1, す: 2, せ: 3, そ: 2, た: 4, ち: 3, つ: 1, て: 2, と: 2,
  な: 5, に: 3, ぬ: 4, ね: 4, の: 1, は: 6, ひ: 2, ふ: 4, へ: 1, ほ: 6,
  ま: 4, み: 3, む: 4, め: 2, も: 3, や: 3, ゆ: 2, よ: 3,
  ら: 3, り: 2, る: 2, れ: 2, ろ: 2, わ: 3, ゐ: 3, ゑ: 4, を: 4, ん: 2,
  っ: 1, ゃ: 3, ゅ: 2, ょ: 3, ぁ: 3, ぃ: 2, ぅ: 2, ぇ: 3, ぉ: 4, ゎ: 3,
  ア: 2, イ: 2, ウ: 3, エ: 3, オ: 3, カ: 2, キ: 3, ク: 2, ケ: 3, コ: 2,
  サ: 3, シ: 3, ス: 2, セ: 2, ソ: 2, タ: 3, チ: 3, ツ: 3, テ: 3, ト: 2,
  ナ: 2, ニ: 2, ヌ: 2, ネ: 4, ノ: 1, ハ: 2, ヒ: 2, フ: 1, ヘ: 1, ホ: 4,
  マ: 2, ミ: 3, ム: 2, メ: 2, モ: 3, ヤ: 2, ユ: 2, ヨ: 3,
  ラ: 2, リ: 2, ル: 2, レ: 1, ロ: 3, ワ: 2, ヲ: 3, ン: 2,
  ッ: 3, ャ: 2, ュ: 2, ョ: 3, ァ: 2, ィ: 2, ゥ: 3, ェ: 3, ォ: 3, ヮ: 2,
  ー: 1, 々: 3,
};

/** Voiced marks add strokes: 濁点 two, 半濁点 one. */
const DAKUTEN = new Map();
for (const [base, extra] of [['\\u3099', 2], ['\\u309A', 1]]) void [base, extra];

/**
 * Strokes for one character, or null when it is not in any table.
 * Returning null rather than guessing keeps an unknown character visible
 * instead of silently skewing the total.
 */
export function strokesOf(ch) {
  if (LOOKUP.has(ch)) return LOOKUP.get(ch);
  if (Object.prototype.hasOwnProperty.call(KANA, ch)) return KANA[ch];
  // Decompose 濁点 / 半濁点: が = か + 2, ぱ = は + 1.
  const decomposed = ch.normalize('NFD');
  if (decomposed.length === 2) {
    const base = KANA[decomposed[0]];
    if (base !== undefined) {
      if (decomposed[1] === '\\u3099') return base + 2;
      if (decomposed[1] === '\\u309A') return base + 1;
    }
  }
  return null;
}

void DAKUTEN;
`;

writeFileSync(join(ROOT, 'app/engine/strokes.js'), body);
console.log(`wrote app/engine/strokes.js — ${total} kanji, ${Object.keys(table).length} distinct counts`);
