/**
 * Generate the service worker.
 *
 * The point of the worker is that the app keeps working with no network at all.
 * That only holds if *every* file the pages reach for is in the cache — one
 * missed module and the app opens to a blank screen offline, which is a worse
 * failure than not being installable. A hand-written list drifts the first time
 * somebody adds an engine module, so the list is generated from the files that
 * are actually on disk, and tools/verify.mjs re-derives it and fails if it has
 * gone stale.
 *
 * The version is a hash of the cached files' contents, so the worker updates
 * exactly when something it serves has changed, and never otherwise.
 *
 * This does not weaken "no network after load" (§7) — it strengthens it. Nothing
 * new is sent; the worker only answers with same-origin bytes it already has.
 *
 * Run:  node tools/build-sw.mjs
 * Writes sw.js.
 */

import { readFileSync, writeFileSync, readdirSync, statSync } from 'node:fs';
import { join, dirname, relative } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createHash } from 'node:crypto';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');

/** Everything the two pages need in order to run with the network switched off. */
export function cacheList() {
  const files = [
    './',
    'index.html',
    'voice.html',
    'manifest.webmanifest',
    'app/style.css',
    // The Emscripten runtime plus its packed data — the .se1 ephemeris files
    // live inside swisseph.data, so that single file is the whole almanac.
    'vendor/swisseph-wasm/src/swisseph.js',
    'vendor/swisseph-wasm/wasm/swisseph.js',
    'vendor/swisseph-wasm/wasm/swisseph.wasm',
    'vendor/swisseph-wasm/wasm/swisseph.data',
  ];

  const walk = (dir) => {
    for (const name of readdirSync(join(ROOT, dir)).sort()) {
      const rel = `${dir}/${name}`;
      if (statSync(join(ROOT, rel)).isDirectory()) walk(rel);
      else if (/\.(js|css|png|svg)$/.test(name)) files.push(rel);
    }
  };
  walk('app');

  return [...new Set(files)];
}

/** A version that changes exactly when the served bytes change. */
export function cacheVersion(files = cacheList()) {
  const hash = createHash('sha256');
  for (const file of files) {
    if (file === './') continue;
    hash.update(file);
    hash.update(readFileSync(join(ROOT, file)));
  }
  return hash.digest('hex').slice(0, 12);
}

const files = cacheList();
const version = cacheVersion(files);

const body = `/**
 * Offline cache.
 *
 * GENERATED by tools/build-sw.mjs — do not edit by hand, re-run it.
 *
 * Precaches every file the two pages need, so the app works with the network
 * switched off. It answers only with same-origin bytes it already holds: no
 * request is added, and "no network after load" (§7) is strengthened, not
 * weakened.
 *
 * Cache-first, because none of these files change without the version below
 * changing with them — the version is a hash of their contents.
 */

const VERSION = '${version}';
const CACHE = \`meishiki-\${VERSION}\`;

const FILES = ${JSON.stringify(files, null, 2)};

self.addEventListener('install', (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    // addAll is atomic: one 404 and the whole install fails, which is what we
    // want. A half-populated cache is the blank-screen failure.
    await cache.addAll(FILES);
    await self.skipWaiting();
  })());
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    for (const key of await caches.keys()) {
      if (key.startsWith('meishiki-') && key !== CACHE) await caches.delete(key);
    }
    await self.clients.claim();
  })());
});

self.addEventListener('fetch', (event) => {
  const { request } = event;
  if (request.method !== 'GET') return;

  const url = new URL(request.url);
  // Same-origin only. The app makes no cross-origin requests, and a worker that
  // would proxy one is a worker that could hide one.
  if (url.origin !== self.location.origin) return;

  event.respondWith((async () => {
    const cached = await caches.match(request, { ignoreSearch: true });
    if (cached) return cached;
    try {
      return await fetch(request);
    } catch {
      // Offline and not in the cache: a navigation still gets the board page
      // rather than the browser's error screen.
      if (request.mode === 'navigate') {
        const shell = await caches.match('index.html');
        if (shell) return shell;
      }
      throw new Error('offline and not cached');
    }
  })());
});
`;

writeFileSync(join(ROOT, 'sw.js'), body);

const bytes = files
  .filter((f) => f !== './')
  .reduce((n, f) => n + statSync(join(ROOT, f)).size, 0);
console.log(`wrote sw.js — ${files.length} files, ${(bytes / 1024 / 1024).toFixed(2)} MB, version ${version}`);
